import type { Metadata } from "next";

import "./globals.css";
import AppLayout from "@/components/shared/app-layout";
import { poppins } from "@/fonts";

export const metadata: Metadata = {
  title: "E-shop | Online Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
